"""Generate canva-app/src/course/* from the ORIGINAL course sources (index.html + assets/). No content changes."""
from pathlib import Path
import json,re,shutil
root=Path(__file__).resolve().parents[1];out=root/'canva-app/src/course';(out/'artwork').mkdir(parents=True,exist_ok=True)
HDR='/* eslint-disable */\n// @ts-nocheck\n// GENERATED by tools/build_app_course.py from the original course sources. Do not edit.\n'
html=(root/'index.html').read_text()
body=re.search(r'<body[^>]*>(.*)</body>',html,re.S)[1]
body=re.sub(r'<script src="[^"]+"></script>','',body)
css='\n'.join((root/'assets'/f).read_text() for f in ['utilities.css','base.css','course.css'])
(out/'courseBody.ts').write_text(HDR+'export default '+json.dumps(body)+';\n')
(out/'courseCss.ts').write_text(HDR+'export default '+json.dumps(css)+';\n')
names=sorted(p.stem for p in (root/'assets/artwork').glob('*.png'))
for n in names:shutil.copy(root/'assets/artwork'/f'{n}.png',out/'artwork'/f'{n}.png')
js='\n'.join((root/'assets'/f).read_text() for f in ['players.js','course.js','enhancements.js'])
js=re.sub(r"(['\"])assets/artwork/([^'\"\s]+)\.png\1",lambda m:'ART["%s"]'%m[2],js)
decl=set(re.findall(r'function\s+([A-Za-z_$][\w$]*)\s*\(',js))
used=set(re.findall(r'onclick=\\?["\']\s*([A-Za-z_$][\w$]*)\s*\(',html+js))
fns=sorted(used);undeclared=sorted(used-decl)
imports=''.join(f'import a{i} from "./artwork/{n}.png";\n' for i,n in enumerate(names))
art='const ART = {'+','.join(f'"{n}": a{i}' for i,n in enumerate(names))+'};\n'
(out/'courseApp.ts').write_text(HDR+imports+art+'export function startCourse() {\n'+('var '+','.join(undeclared)+';\n' if undeclared else '')+js+'\nObject.assign(window, {'+','.join(fns)+'});\n}\n')
print(len(fns),'functions exported;',len(names),'images')
